import {
  b1,
  b10,
  b2,
  b3,
  b4,
  b5,
  b6,
  b7,
  b8,
  b9,
  bits1,
  bits2,
  bits3,
  bits4,
  bits5,
  bits6,
  bits7,
  bits8,
  dalle1,
  dalle2,
  dalle3,
  dalle4,
  dalle5,
  dalle6,
  dalle7,
  dalle8,
  dp1,
  dp2,
  dp3,
  dp4,
  dp5,
  dp6,
  dp7,
  ea1,
  ea2,
  ea3,
  ea4,
  ea5,
  ea6,
  ea7,
  ea8,
  gulf2,
  gulf3,
  gulf4,
  gulf5,
  gulf6,
  gulf7,
  gulf8,
  gulfmarina1,
  mx1,
  mx2,
  mx3,
  mx4,
  mx5,
  mx6,
  mx7,
  mx8,
} from "assets";

export const data = [
  {
    title: "Gulf Marina",
    category: "ui/ux",
    mainImage: gulfmarina1,
    description: `Gulf Marina is a comprehensive cargo website designed to facilitate seamless transportation and logistics services. With a focus on the maritime industry, Gulf Marina offers efficient cargo solutions to businesses and individuals alike. The website features an intuitive user interface, allowing users to easily navigate through various cargo services and access vital information. The website showcases a wide range of shipping options tailored to meet different cargo needs, including sea freight, air freight, and land transportation. \n The website is built with a responsive design, allowing users to access its functionalities seamlessly across various devices, including desktops, tablets, and smartphones. Gulf Marina prioritizes exceptional customer support, providing a dedicated team to address queries, provide assistance, and offer guidance throughout the shipping process. \n Overall, Gulf Marina's cargo website showcases a commitment to excellence in the transportation industry, empowering businesses and individuals to optimize their logistics operations effectively.
    `,
    images: [gulfmarina1, gulf2, gulf3, gulf4, gulf5, gulf6, gulf7, gulf8],
    date: "May 22, 2023",
    duration: "15 Days",
    link: "http://gulfmarina1.com",
  },
  {
    title: "Enter App",
    category: "frontend",
    mainImage: ea1,
    description: ` Enter App is a visually captivating and innovative platform that offers a range of exciting functionalities catering to the world of cryptocurrencies and NFTs (Non-Fungible Tokens). With its vibrant tokenomics section and beautifully outlined roadmap, Enter App is poised to revolutionize the way users interact with digital assets. \n Enter App provides users with a gateway to an expansive NFT marketplace, where they can discover and trade a diverse collection of unique digital assets. From digital art to virtual collectibles, users can explore a myriad of NFTs from various artists and creators. One of the standout features of Enter App is its lightning-fast instant swapping functionality. Users can seamlessly exchange different cryptocurrencies and NFTs within the platform, simplifying the process of diversifying their digital portfolios. \n Enterr App combines aesthetic appeal with cutting-edge functionalities, making it an enticing destination for crypto enthusiasts, collectors, and investors alike. Its commitment to user experience, security, and continuous improvement positions it as a frontrunner in the ever-evolving world of blockchain-based services.
    `,
    images: [ea1, ea2, ea3, ea4, ea5, ea6, ea7, ea8],
    date: "July 26, 2023",
    duration: "15 Days",
    link: "https://enter-app-afb41.web.app/",
  },

  {
    title: "Dalle INU",
    category: "frontend",
    mainImage: dalle1,
    description: `Dalle Inu is a visually stunning project that introduces a groundbreaking concept in the world of blockchain and NFTs. With its captivating theme in yellow and brown colors, the platform incorporates elegant wave effects after each section, adding a touch of aesthetic appeal that enhances the overall user experience. Dalle Inu pioneers the use of artificial intelligence in generating unique and artistic images. Leveraging advanced AI algorithms, users can create one-of-a-kind visuals that serve as the foundation for the creation of exclusive NFTs. \n The platform seamlessly transforms the AI-generated images into non-fungible tokens (NFTs). These NFTs represent the originality and ownership of the artwork, enabling users to monetize their creations in the growing NFT marketplace. Dalle Inu's choice of yellow and brown colors exudes warmth and creativity, creating a visually harmonious environment that resonates with users and artists alike. \n Dalle Inu ensures an intuitive user interface, allowing users to seamlessly navigate through the AI image generation process, NFT creation, and other features of the platform with ease. By leveraging blockchain technology, Dalle Inu ensures the security, authenticity, and permanence of each NFT, empowering artists and collectors to engage in a trustworthy and decentralized ecosystem. \n The combination of cutting-edge AI technology, NFT integration, and stunning visual design elevates Dalle Inu to a league of its own. As the first blockchain platform to enable AI-powered image generation and NFT creation, Dalle Inu opens new doors of opportunity for artists and enthusiasts in the emerging world of digital art and collectibles.
    `,
    images: [dalle1, dalle2, dalle3, dalle4, dalle5, dalle6, dalle7, dalle8],
    date: "February 10, 2023",
    duration: "1 Month",
    link: "https://dalleinu.ai/",
  },
  {
    title: "MX100",
    category: "frontend",
    mainImage: mx1,
    description: `MX100 was a visually captivating and futuristic website dedicated to promoting the first-ever awards event celebrating metaverse-based solutions. The website, adorned with a beautiful greenish color scheme, served as a hub of information for the prestigious event scheduled to take place on December 20, 2022, at the iconic Burj Khalifa in Dubai. MX100 embraced a futuristic design approach, reflecting the cutting-edge nature of metaverse-based solutions. The website's aesthetics and layout provided a glimpse of the innovative and immersive event to come. The greenish color theme of MX100 symbolized growth, innovation, and sustainability, aligning perfectly with the theme of metaverse technology and its potential to reshape the future. \n The website acted as a comprehensive repository of event information, including the date, time, and location of the award ceremony. It also featured details about the various award categories, nominations, and esteemed guests attending the event.  MX100 showcased various metaverse-based solutions and projects, offering visitors a glimpse into the cutting-edge technologies and applications driving the metaverse revolution. The website featured a roster of industry-leading speakers, experts, and visionaries who would be delivering keynote speeches and participating in panel discussions during the event. \n MX100 aimed to recognize the remarkable innovations and advancements in the metaverse space, bridging the gap between virtual and physical realities. As the first-of-its-kind awards event in this domain, MX100 held the potential to be a landmark occasion, inspiring future generations of creators and entrepreneurs to explore the limitless possibilities of the metaverse.
    `,
    images: [mx1, mx2, mx3, mx4, mx5, mx6, mx7, mx8],
    date: "November 20, 2022",
    duration: "15 Day",
  },
  {
    title: "Decentrapad",
    category: "frontend",
    mainImage: dp5,
    description: ` Decentrapad is an ambitious and versatile project that empowers users to unleash their creativity in the world of decentralized finance. With its captivating darkish green color scheme and a seamless user experience, Decentrapad offers two major parts: the main platform for creating launchpads and tokens, and 0x, a hub for turning creative ideas into reality through crowdfunding and community support. At the heart of Decentrapad lies the capability for users to create their own tokens effortlessly. With a user-friendly interface, creators can define the unique attributes and properties of their tokens, giving them a distinct identity in the market. Additionally, Decentrapad facilitates the creation of launchpads, enabling smooth token sales and distribution. \n Decentrapad streamlines the process of token sales, allowing users to list and sell their newly created tokens within seconds. This efficient mechanism empowers creators to bring their projects to the market swiftly and without unnecessary delays. The platform prioritizes security by leveraging blockchain technology, ensuring that all transactions, token transfers, and sales are executed with utmost safety and transparency. \n The 0x section of Decentrapad is a creative haven where aspiring entrepreneurs and innovators can share their project ideas and seek community support to bring those ideas to life.  Users can post their project concepts and ideas on the 0x platform, describing their vision and objectives clearly.  Other users and the broader community can explore these project proposals and, if they resonate with the idea, contribute funds to support its development and execution. This collaborative funding approach fosters a sense of community and encourages innovative projects to flourish. \n Decentrapad's commitment to simplicity, security, and community collaboration makes it an empowering force in the realm of decentralized finance and project incubation. By facilitating token creation and supporting budding entrepreneurs, Decentrapad plays a crucial role in shaping the future of decentralized ecosystems.
    `,
    images: [dp1, dp2, dp3, dp4, dp5, dp6, dp7],
    date: "January 1, 2023",
    duration: "8 Months",
    link: "https://decentrapad.web.app/",
  },
  {
    title: "BIT's App",
    category: "frontend",
    mainImage: bits1,
    description: `Bit's App is a revolutionary platform that seeks to challenge the stigmas surrounding street performing artists by acknowledging their talent and value in society. With a captivating red and black theme, complemented by moments of white and red accents, the app offers a unique blend of dark and light mode functionality. Bit's App is on a mission to redefine the perception of street performing artists, recognizing them as skilled and talented individuals rather than just being limited to public spaces. The vision is brought to life by Snap Boogie, who aims to break stereotypes and elevate street artists to new heights of respect and admiration for their authenticity and integrity. \n Bit's App aims to empower street artists by showcasing the true quality of their performances and talents. By embracing the NFT (Non-Fungible Token) technology, the app transforms their dance moves and performing moments into video-game emotes as valuable digital assets. Bit's App revolutionizes the connection between street artists and their fans by turning their iconic dance moves and performances into unique video-game emote NFTs. These NFTs not only provide a novel way for fans to engage with their favorite artists but also offer the artists the potential for intellectual property ownership in the growing NFT industry. The red and black theme predominantly dominates the app's design, reflecting its bold and passionate vision for celebrating street performing artists. Hints of white and red accents add a dynamic touch, enhancing the visual experience for users. \n Bit's App stands as a pioneering platform, leveraging technology and creativity to transform the way street artists are perceived and celebrated. By providing a space for artists to connect with their fans through unique NFT emotes, the app brings the worlds of arts, gaming, and NFTs together for an innovative and empowering experience.
    `,
    images: [bits1, bits2, bits3, bits4, bits5, bits6, bits7, bits8],
    date: "Oct 15, 2022",
    duration: "6 Months",
    link: "https://bits-enjin.web.app/",
  },
  {
    title: "Buna",
    category: "frontend",
    mainImage: b1,
    description: ` Buna is a beautifully crafted platform, offering a unique challenge of accommodating both right-to-left (Arabic) and left-to-right (English) content seamlessly. With its captivating sky blueish and white color theme, Buna provided users with a versatile and engaging user experience, enriched with a plethora of innovative features. Buna embraced its multilingual audience by providing language options for both English and Arabic. With a simple click of a button, users could effortlessly switch between languages. \n The platform boasted a custom-designed video player and audio player, enabling users to watch and listen to a diverse collection of videos and audio content curated by Buna's management. Buna kept its users up-to-date with the latest trends and insights in various fields through a repository of articles and conference materials. By accessing the most recent information, users could stay ahead of the curve and remain informed about industry developments. \n The platform featured a comprehensive video and audio library, providing a rich resource for learners to explore and delve deeper into specific topics of interest. \n Buna's successful execution of right-to-left and left-to-right content, coupled with its diverse learning resources and language support, made it a standout project in the world of web development and design. By offering a dynamic and interactive user experience, Buna effectively bridged the gap between education and technology, making it an indispensable tool for knowledge seekers.
    `,
    images: [b1, b2, b3, b4, b5, b6, b7, b8, b9, b10],
    date: "April 20, 2023",
    duration: "2 Months",
  },
];
